<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Enums\BroadcastEvent;
use Illuminate\Console\Command;
use Illuminate\Filesystem\Filesystem;

class GenerateEchoPayloadTypes extends Command
{
    protected $signature = 'app:generate-echo-payload-types {--path=}';

    protected $description = 'Generate TypeScript payload types for broadcast events discovered by Wayfinder';

    public function __construct(
        private readonly Filesystem $files,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $path = $this->option('path');

        if (! is_string($path) || '' === $path) {
            $this->error('The --path option is required.');

            return self::FAILURE;
        }

        $this->writePayloadTypes($path);

        $this->info("Echo payload types written to [{$path}].");

        return self::SUCCESS;
    }

    private function writePayloadTypes(string $path): void
    {
        $payloadEntries = collect($this->payloadTypes())
            ->map(fn (string $payloadType, string $eventName): string => "    '{$eventName}': {$payloadType};")
            ->implode(PHP_EOL);

        $content = implode(PHP_EOL, [
            '// This file is auto-generated from Laravel broadcast events.',
            '// Do not edit this file directly, any changes will be overwritten.',
            '',
            'export type EchoNotificationPayloads = {',
            $payloadEntries,
            '};',
            '',
            'export type EchoNotificationEventName = keyof EchoNotificationPayloads;',
            '',
            'export type EchoNotificationPayload<TEvent extends EchoNotificationEventName> =',
            '    EchoNotificationPayloads[TEvent];',
            '',
        ]);

        $this->files->ensureDirectoryExists($path);
        $this->files->put("{$path}/echo-notification-payloads.ts", $content);
    }

    /** @return array<string, string> */
    private function payloadTypes(): array
    {
        return [
            '.'.BroadcastEvent::NewOrderForVendor->value => 'App.Data.Broadcast.VendorOrderBroadcastData',
            '.'.BroadcastEvent::CustomerOrderStatusChanged->value => 'App.Data.Broadcast.VendorOrderBroadcastData',
            '.'.BroadcastEvent::VendorApplicationStatusUpdated->value => 'App.Data.Broadcast.VendorApplicationStatusBroadcastData',
            '.'.BroadcastEvent::WithdrawalRequestApproved->value => 'App.Data.Broadcast.WithdrawalApprovedBroadcastData',
            '.'.BroadcastEvent::LivestreamCreated->value => 'App.Data.LivestreamData',
            '.'.BroadcastEvent::LivestreamUpdated->value => 'App.Data.LivestreamData',
            '.'.BroadcastEvent::LivestreamCommentCreated->value => 'App.Data.Broadcast.LivestreamCommentBroadcastData',
            '.'.BroadcastEvent::LivestreamLikeCountUpdated->value => 'App.Data.Broadcast.LivestreamLikeCountBroadcastData',
        ];
    }
}
