<?php

declare(strict_types=1);

namespace App\Console\Commands;

use Laravel\Ranger\Ranger;
use Illuminate\Console\Command;
use Illuminate\Support\Collection;
use Illuminate\Filesystem\Filesystem;
use Laravel\Wayfinder\Langs\TypeScript;
use Laravel\Ranger\Components\BroadcastEvent;
use Laravel\Wayfinder\Registry\ResultConverter;
use Laravel\Wayfinder\Registry\TypeScriptConverter;

class GenerateEchoPayloadTypes extends Command
{
    protected $signature = 'app:generate-echo-payload-types {--path=}';

    protected $description = 'Generate TypeScript payload types for broadcast events discovered by Wayfinder';

    public function __construct(
        private readonly Filesystem $files,
        private readonly Ranger $ranger,
    ) {
        parent::__construct();
    }

    public function handle(): int
    {
        $path = $this->option('path');

        if (! is_string($path) || '' === $path) {
            $this->error('The --path option is required.');

            return self::FAILURE;
        }

        $this->ranger->onBroadcastEvents(function (Collection $events) use ($path): void {
            $this->writePayloadTypes($events, $path);
        });

        ResultConverter::register(TypeScriptConverter::class);
        $this->ranger->setAppPaths(app_path());
        $this->ranger->setBasePaths(base_path());
        $this->ranger->walk();

        $this->info("Echo payload types written to [{$path}].");

        return self::SUCCESS;
    }

    /**
     * @param  Collection<int, BroadcastEvent>  $events
     */
    private function writePayloadTypes(Collection $events, string $path): void
    {
        $events = $events
            ->unique(fn (BroadcastEvent $event) => $event->name)
            ->values();

        $payloadEntries = $events
            ->map(function (BroadcastEvent $event): string {
                return '    '.(string) TypeScript::objectKeyValue(
                    $this->eventName($event),
                    (string) TypeScript::objectToTypeObject($event->data->value, false),
                ).';';
            })
            ->implode(PHP_EOL);

        $content = implode(PHP_EOL, [
            '// This file is auto-generated from Laravel broadcast events.',
            '// Do not edit this file directly, any changes will be overwritten.',
            '',
            "import type {App} from './types';",
            '',
            'export type EchoNotificationPayloads = {',
            $payloadEntries,
            '};',
            '',
            'export type EchoNotificationEventName = keyof EchoNotificationPayloads;',
            '',
            'export type EchoNotificationPayload<TEvent extends EchoNotificationEventName> =',
            '    EchoNotificationPayloads[TEvent];',
            '',
        ]);

        $this->files->ensureDirectoryExists($path);
        $this->files->put("{$path}/echo-notification-payloads.ts", $content);
    }

    private function eventName(BroadcastEvent $event): string
    {
        return '.'.str_replace('\\', '.', $event->name);
    }
}
